import './globals.css'
import moglanFont from '@/utils/FontLoader'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={moglanFont.className}>{children}</body>
    </html>
  )
}
